
# Build stage
FROM node:22 AS build

WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# # Expose port 80
EXPOSE 4000

# Start Nginx
CMD ["npm", "run", "dev"]
